[package]
name = "ramen"
version = "0.0.1"

[[bin]]
name = "ramen"
path = "ramen.rs"

[dependencies]
reqwest = { version = "0.11.9", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
